apiVersion: v1
type: Service
metadata:
    name: postgres-cluster-ip-service
spec:
    type: ClusterIP
    selector:
      component: postgres
    ports:
      - port: 5432
        targetPort: 5432